export { default as Header} from './Header/Header'
export { default as MoviesDetails} from './MovieDetails/MoviesDetails'
export { default as MoviesList} from './MovieList/MoviesList'
export { default as Loading } from './utils/Loading'
export { default as SearchBar } from './SearchBar/SearchBar'